### ISSUE TITLE
Improve Package Description pages.

### ISSUE THREAD

**Issue by dzackgarza** [dzackgarza/hackage-server#3]
- [x] Include package ranking 
- [ ] Improve organization of items displayed.
- [ ] Add external reverse dependencies module?

Specific Ideas from https://github.com/haskell/hackage-server/issues/366:
- [ ] Prominent "Latest" button
- [ ] Display date in ISO format (remove day of week)
- [ ] Move date closer to "Versions"
- [ ] Make package description collapsible with "Read More" link
  (..."but use a div that can be scrolled with a max-height; the button removes the max-height so that it can be viewed in its entirety")
- [ ] Move doc build status to maintainer's corner
- [ ] Upper-left title should link to unversioned package page
- [ ] Make package uploader's name a link
- [ ] Move items above the fold (in order of priority): 
  - Latest Version button and version number
  - Module hierarchy
  - Dependencies list
  - Package homepage/source repository link
  - Number of downloads in last 30 days
  - Collapsed package description

Possible fixes:
- [ ] Create "versions" page, displaying all versions in rows, with metadata (such as upload dates). Link each to versioned page.
- [ ] Display 5 most recent versions, then provide a link to "See All Versions" (link to version page above)

**Comment by dzackgarza** [comment]
Alternative Mockup: <http://code.haskell.org/~duncan/hackage-server-new-chrome/package-2.html>

**Comment by dcoutts** [comment]
> * Move to put the Readme at the bottom of the page: haskell#356 (comment)
> * Rendering Readme.md in package pages: haskell#279

Both done but not yet deployed.

**Comment by dcoutts** [comment]
>  Display 5 most recent versions, then provide a link to "See All Versions" (link to version page above)

So another option here is to display recent "interesting" versions. There's code in cabal-install for the 'info' command to show not just the last N, but the last N that are vaguely interesting, so in particular it shows the last version of earlier major versions.

Have a look at "cabal info $pkgname" and see if you like it, and if so steal and tweak that code.
